// Generated by CoffeeScript 1.3.1
(function() {

  this.Network = (function() {

    Network.name = 'Network';

    function Network() {
      null;

    }

    return Network;

  })();

}).call(this);
