// Generated by CoffeeScript 1.3.1
(function() {

  this.Player = (function() {

    Player.name = 'Player';

    function Player(_arg) {
      var diplomacy, gold, heroes, name;
      name = _arg.name, heroes = _arg.heroes, gold = _arg.gold, diplomacy = _arg.diplomacy;
      this.name = name;
      this.heroes = heroes || [];
      this.gold = gold || 0;
      this.diplomacy = diplomacy || {};
    }

    Player.prototype.ally = function(id) {
      return delete this.diplomacy[id];
    };

    Player.prototype.unally = function(id) {
      return this.diplomacy[id] = true;
    };

    Player.prototype.hero = function(id) {
      return this.heroes[id || 0];
    };

    return Player;

  })();

}).call(this);
