// Generated by CoffeeScript 1.3.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  this.Tile = (function(_super) {

    __extends(Tile, _super);

    Tile.name = 'Tile';

    Tile.prototype.isTile = true;

    function Tile(options) {
      Tile.__super__.constructor.call(this, options);
      this.name = options.name, this.orientations = options.orientations, this.z = options.z, this.walkable = options.walkable, this.swimable = options.swimable, this.flyable = options.flyable;
    }

    Tile.prototype.save = function() {
      return {
        name: this.name,
        z: this.z
      };
    };

    Tile.prototype.orient = function(orientations) {
      var backgrounds, i, layers, name, names, orientation, x, y, _i, _len;
      layers = [];
      backgrounds = [];
      names = orientations.split(' ').reverse();
      i = 0;
      name = void 0;
      for (_i = 0, _len = names.length; _i < _len; _i++) {
        name = names[_i];
        orientation = this.orientations[name];
        x = orientation[0];
        y = orientation[1];
        backgrounds.push('url(' + this.spritemap + ') ' + -x + 'px ' + -y + 'px');
      }
      return this.element.css('background', backgrounds.join(', '));
    };

    return Tile;

  })(Sprite);

}).call(this);
